version: "2"

volumes:
  build: ~
  deps: ~

services:
  cabbage:
    image: elixir:1.7
    entrypoint: mix
    command: do local.hex --force, deps.get, deps.compile, test --only integration
    environment:
      MIX_ENV: test
    working_dir: /code
    volumes:
      - .:/code
      - build:/code/_build
      - deps:/code/deps
