version: 2.1

jobs:
  build:
    parameters:
      version:
        description: Elixir version
        type: string
      execute:
        description: What steps to execute after build
        type: steps
        default: []

    parallelism: 1
    docker:
      - image: elixir:<< parameters.version >>

    steps:
      - checkout

      - restore_cache:
          key: testing-elixir-v<< parameters.version >>

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: MIX_ENV=test mix do deps.get --only test, deps.compile, compile

      - save_cache:
          key: testing-elixir-v<< parameters.version >>
          paths:
            - _build
            - deps
            - ~/.mix

      - steps: << parameters.execute >>

workflows:
  version: 2.1
  testing_all_versions:
    jobs:
      - build:
         version: 1.8.1
         execute:
           - run: mix test
      - build:
         version: 1.7.4
         execute:
           - run: mix test
      - build:
         version: 1.6.6
         execute:
           - run: mix test
      - build:
         version: 1.5.3
         execute:
           - run: mix test
      - build:
         version: 1.4.5
         execute:
           - run: mix test
      - build:
         version: 1.3.4
         execute:
           - run: mix test
  validate_code_quality:
    jobs:
      - build:
          version: 1.8.1
          execute:
            - run:
                command: MIX_ENV=test mix coveralls.circle
                environment:
                  COVERALLS_REPO_TOKEN: 5wI8JIzygEDIF4A03KNIKWdOmVK2A8dMC
      - build:
          version: 1.8.1
          execute:
            - run: mix format --check-formatted
